### ISSUE TITLE
Adding visible/invisible classes

### ISSUE THREAD

**Issue by eliquious** [johnotander/rework-flex-grid#5]
What do you think about including visible/invisible classes in the generator? You may have noticed [this project](https://github.com/eliquious/rework-visibility) already but I've started a first go at the classes. It's basically Bootstrap's hidden/visible classes inside rework's media queries.. Like I said, It's a draft. The classes are exactly the same for each media query but with a different name. I think it lends itself well to being generated. Thoughts?

**Comment by johnotander** [comment]
I did notice that project, looks cool!

I think that it's definitely worth considering adding to the generator. It almost feels like a mixing of concerns; though, it is something that can fall under the concern of the grid. Especially since these CSS modules will share breakpoints and would be quite handy for hiding/showing columns. It's a tricky thing to consider.

The visible/invisible classes definitely lend themselves well to being generated, but you can also leverage [rework custom media](https://github.com/reworkcss/rework-custom-media/) to handle this functionality as well. Since, the classes won't be as dynamic as the columns of a grid. Instead, the dynamic portion would be breakpoints which can be set with [rework vars](https://github.com/reworkcss/rework-vars) and custom media.

I will have to ponder this one a bit further, though.

**Comment by eliquious** [comment]
Yeah, that's a good point. I do think using those rework extensions would allow this flexibility without adding it specifically to the generator.

**Comment by johnotander** [comment]
Absolutely, as I ponder it a bit more, I think this is probably the best way to go. That way, the `src` directory files can contain the rework variables and custom media, and then a gulpfile can build it to raw CSS. This would allow those that want a customized build, can modify it themselves (variables), and then rerun it.

You should be able just to hoist the rework task from any of the projects in https://github.com/markdowncss as you'll need something like:

```js
var gulp = require('gulp'),
    name = require('gulp-rename'),
    rework = require('gulp-rework'),
    reworkVars = require('rework-vars'),
    classPrefix = require('rework-class-prefix'),
    media  = require('rework-custom-media');

gulp.task('css', function() {
  return gulp.src('index.css')
    .pipe(rework(reworkNPM(), classPrefix('splendor-'), media(), reworkVars()))
    .pipe(size({ gzip: true, showFiles: true }))
    .pipe(name('splendor.css'))
    .pipe(gulp.dest('css'));
});
```

**Comment by johnotander** [comment]
Feel free to ping me if you need any more input on this, :beers:
